### PR TITLE
Add URL and dependencies for new tracker

### PR DESCRIPTION
**Pull request by Tomcli**
We would like to have this journey also sent metrics to our new tracker to see its behavior. 
- Add the new tracker SDK package, SDK call, and the metadata file(repository.yaml)
- Update privacy notice

cc: @animeshsingh

### CODE REVIEW

**Review by stevemar — APPROVED** [review]
i much prefer this approach of using both while the metrics-tracker continue to bake in the oven +1

**Comment by animeshsingh** [comment]
Thanks @Tomcli - Also add the badges from the new repo to this one. This will reset the counter- and thinking more about it, @stevemart are you fine starting from scratch, else we can explore starting from 500

**Comment by animeshsingh** [comment]
hey folks - what is this waiting on?

**Comment by stevemar** [comment]
why was this closed?

**Comment by animeshsingh** [comment]
Think this was a mistake

**Comment by stevemar** [comment]
@animeshsingh OK, i can merge it now, can you confirm that things are ready on your end? @scottdangelo last chance to review

**Comment by scottdangelo** [comment]
Done

**Pull request merged**
